# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-14 22:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Planet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('seed', models.BigIntegerField(default=0)),
                ('population_qty', models.IntegerField(default=0, verbose_name='Population Amout')),
                ('missiles_qty', models.IntegerField(default=0, verbose_name='Missile Amount')),
                ('shield_qty', models.IntegerField(default=0, verbose_name='Shield Amount')),
                ('population_distr', models.IntegerField(default=100, verbose_name='Planet Population %')),
                ('shield_distr', models.IntegerField(default=0, verbose_name='Planet Shield %')),
                ('missiles_distr', models.IntegerField(default=0, verbose_name='Planet Missile %')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=20, verbose_name='Room Name')),
                ('room_num', models.IntegerField(verbose_name='Room Number')),
                ('pub_date', models.DateTimeField(verbose_name='Date added')),
                ('game_started', models.BooleanField(default=0, verbose_name='Game started (True/False)')),
                ('max_players', models.IntegerField(default=0, verbose_name='Room players limit')),
                ('connected_players', models.IntegerField(default=0, verbose_name='Amount of players online')),
                ('bot_players', models.IntegerField(default=0, verbose_name='Amount of bot players')),
                ('missile_delay', models.IntegerField(default=2, verbose_name='Missile Delay')),
                ('init_population', models.IntegerField(default=0, verbose_name='Initial Population')),
                ('const_population', models.IntegerField(default=1, verbose_name='Population Generation Constant')),
                ('const_shield', models.IntegerField(default=1, verbose_name='Shield Generation Constant')),
                ('const_missile', models.IntegerField(default=1, verbose_name='Missile Generation Constant')),
                ('population_damage_per_missile', models.IntegerField(default=1, verbose_name='Population damage per missile')),
                ('shield_damage_per_missile', models.IntegerField(default=1, verbose_name='Shield damage per missile')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Room Creator')),
            ],
        ),
        migrations.AddField(
            model_name='planet',
            name='gameroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Room'),
        ),
        migrations.AddField(
            model_name='planet',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
