# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-22 02:45
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_name', models.CharField(default='Default Name', max_length=20, verbose_name='Game Name')),
                ('pub_date', models.DateTimeField(verbose_name='Date added')),
                ('game_started', models.BooleanField(default=0, verbose_name='Game started (True/False)')),
                ('max_players', models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(2)], verbose_name='Game players limit')),
                ('connected_players', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Amount of players online')),
                ('bot_players', models.IntegerField(default=2, validators=[django.core.validators.MinValueValidator(2)], verbose_name='Amount of bot players')),
                ('time_misil', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Missile Delay')),
                ('initial_population', models.IntegerField(default=5000, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Initial Population')),
                ('const_population', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Population Generation Constant')),
                ('const_shield', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Shield Generation Constant')),
                ('const_missile', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Missile Generation Constant')),
                ('hurt_to_population', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Population damage per missile')),
                ('hurt_to_shield', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Shield damage per missile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Game user')),
            ],
        ),
        migrations.CreateModel(
            name='Missile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('launch_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Planet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Planet name')),
                ('seed', models.BigIntegerField(default=0, verbose_name='Planet seed')),
                ('population_qty', models.IntegerField(default=5000, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Population Amout')),
                ('missiles_qty', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Missile Amount')),
                ('shield_perc', models.IntegerField(default=100, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Shield Amount')),
                ('population_distr', models.IntegerField(default=100, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Planet Population %')),
                ('shield_distr', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Planet Shield %')),
                ('missile_distr', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Planet Missile %')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='missile',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='game.Planet'),
        ),
        migrations.AddField(
            model_name='missile',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target', to='game.Planet'),
        ),
    ]
