# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-12 23:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_poblation', models.IntegerField(default=1)),
                ('const_misil', models.IntegerField(default=1)),
                ('const_shield', models.IntegerField(default=1)),
                ('const_poblation', models.IntegerField(default=1)),
                ('time_misil', models.IntegerField(default=1)),
                ('hurt_to_poblation', models.IntegerField(default=1)),
                ('hurt_to_shield', models.IntegerField(default=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='game',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='gameplanet',
            name='game',
        ),
        migrations.RemoveField(
            model_name='gameplanet',
            name='planet',
        ),
        migrations.AlterField(
            model_name='gamebot',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Partida'),
        ),
        migrations.DeleteModel(
            name='Game',
        ),
        migrations.DeleteModel(
            name='GamePlanet',
        ),
        migrations.AddField(
            model_name='planet',
            name='game',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='game.Partida'),
        ),
    ]
