# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-17 03:51
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_remove_room_room_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planet',
            name='missiles_distr',
        ),
        migrations.RemoveField(
            model_name='planet',
            name='shield_qty',
        ),
        migrations.AddField(
            model_name='planet',
            name='missile_distr',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Planet Missile %'),
        ),
        migrations.AddField(
            model_name='planet',
            name='shield_perc',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Shield Amount'),
        ),
        migrations.AlterField(
            model_name='planet',
            name='missiles_qty',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Missile Amount'),
        ),
        migrations.AlterField(
            model_name='planet',
            name='population_distr',
            field=models.IntegerField(default=100, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Planet Population %'),
        ),
        migrations.AlterField(
            model_name='planet',
            name='population_qty',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Population Amout'),
        ),
        migrations.AlterField(
            model_name='planet',
            name='shield_distr',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Planet Shield %'),
        ),
    ]
