# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-13 02:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game', '0003_auto_20171013_0214'),
    ]

    operations = [
        migrations.CreateModel(
            name='Planet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('population_qty', models.IntegerField(default=0)),
                ('missils_qty', models.IntegerField(default=0)),
                ('shield_power', models.IntegerField(default=100)),
                ('population_res', models.IntegerField(default=100)),
                ('shield_res', models.IntegerField(default=0)),
                ('missils_res', models.IntegerField(default=0)),
                ('game', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='game.Partida')),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
