# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-17 04:13
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_auto_20171017_0351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planet',
            name='population_qty',
            field=models.IntegerField(default=5000, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Population Amout'),
        ),
        migrations.AlterField(
            model_name='room',
            name='bot_players',
            field=models.IntegerField(default=2, validators=[django.core.validators.MinValueValidator(2)], verbose_name='Amount of bot players'),
        ),
        migrations.AlterField(
            model_name='room',
            name='connected_players',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Amount of players online'),
        ),
        migrations.AlterField(
            model_name='room',
            name='const_missile',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Missile Generation Constant'),
        ),
        migrations.AlterField(
            model_name='room',
            name='const_population',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Population Generation Constant'),
        ),
        migrations.AlterField(
            model_name='room',
            name='const_shield',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Shield Generation Constant'),
        ),
        migrations.AlterField(
            model_name='room',
            name='init_population',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Initial Population'),
        ),
        migrations.AlterField(
            model_name='room',
            name='max_players',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(2)], verbose_name='Room players limit'),
        ),
        migrations.AlterField(
            model_name='room',
            name='missile_delay',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Missile Delay'),
        ),
        migrations.AlterField(
            model_name='room',
            name='population_damage_per_missile',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Population damage per missile'),
        ),
        migrations.AlterField(
            model_name='room',
            name='shield_damage_per_missile',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Shield damage per missile'),
        ),
    ]
