# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-13 02:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_planet'),
    ]

    operations = [
        migrations.RenameField(
            model_name='planet',
            old_name='game',
            new_name='gameroom',
        ),
    ]
