# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-17 17:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_auto_20171017_0413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_name',
            field=models.CharField(default='Default Name', max_length=20, verbose_name='Room Name'),
        ),
    ]
