# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-13 03:41
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_auto_20171013_0249'),
    ]

    operations = [
        migrations.RenameField(
            model_name='planet',
            old_name='missils_qty',
            new_name='missile_amm',
        ),
        migrations.RenameField(
            model_name='planet',
            old_name='missils_res',
            new_name='shield_perc',
        ),
        migrations.RemoveField(
            model_name='planet',
            name='population_qty',
        ),
        migrations.RemoveField(
            model_name='planet',
            name='population_res',
        ),
        migrations.RemoveField(
            model_name='planet',
            name='shield_power',
        ),
        migrations.RemoveField(
            model_name='planet',
            name='shield_res',
        ),
        migrations.AddField(
            model_name='planet',
            name='missile_distr',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='planet',
            name='population_amm',
            field=models.IntegerField(default=5000, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='planet',
            name='population_distr',
            field=models.IntegerField(default=100, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='planet',
            name='shield_distr',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='planet',
            name='gameroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Partida'),
        ),
        migrations.AlterField(
            model_name='planet',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
