# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-17 19:43
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_auto_20171017_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='max_players',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(2)], verbose_name='Room players limit'),
        ),
    ]
