# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-16 23:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game', '0006_auto_20171013_0341'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_poblation', models.IntegerField(default=1, help_text=b'please enter values greater than 0.')),
                ('const_misil', models.IntegerField(default=1, help_text=b'please enter values greater than 0.')),
                ('const_shield', models.IntegerField(default=1, help_text=b'please enter values greater than 0.')),
                ('const_poblation', models.IntegerField(default=1, help_text=b'please enter values greater than 0.')),
                ('time_misil', models.IntegerField(default=1, help_text=b'Please enter a number of minutes greater than 0')),
                ('hurt_to_poblation', models.IntegerField(default=1, help_text=b'Please enter a percentage greater than 0')),
                ('hurt_to_shield', models.IntegerField(default=1, help_text=b'Please enter a percentage greater than 0')),
                ('max_players', models.IntegerField(default=2)),
                ('playing', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name=b'User creator')),
            ],
            options={
                'ordering': ['user'],
                'verbose_name_plural': 'Games',
            },
        ),
        migrations.RemoveField(
            model_name='partida',
            name='user',
        ),
        migrations.AlterField(
            model_name='planet',
            name='gameroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Game'),
        ),
        migrations.DeleteModel(
            name='Partida',
        ),
    ]
