# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-18 18:29
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_auto_20171017_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planet',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Planet name'),
        ),
        migrations.AlterField(
            model_name='planet',
            name='seed',
            field=models.BigIntegerField(default=0, verbose_name='Planet seed'),
        ),
        migrations.AlterField(
            model_name='planet',
            name='shield_perc',
            field=models.IntegerField(default=100, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Shield Amount'),
        ),
    ]
