# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-19 13:17
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_auto_20171018_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planet',
            name='shield_perc',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Shield Amount'),
        ),
    ]
