# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-19 17:54
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_auto_20171019_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planet',
            name='shield_perc',
            field=models.IntegerField(default=100, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Shield Amount'),
        ),
    ]
