# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-19 17:57
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_auto_20171019_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='init_population',
            field=models.IntegerField(default=5000, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Initial Population'),
        ),
    ]
